import {
  BookOpen,
  BookText,
  ChartPie,
  Folder,
  IdCard,
  MessageCircle,
  ShoppingBag,
  SquareUser,
  UsersRound,
} from "lucide-react";

export const user = {
  name: "ByeWind",
  image: "/ByeWind.png",
};

export const tabs = [
  {
    label: "Favorites",
    children: [
      { id: "overview", label: "Overview" },
      { id: "projects", label: "Projects" },
    ],
  },
  {
    label: "Recently",
    children: [
      { id: "dashboard", label: "Dashboard" },
      { id: "users", label: "Users" },
    ],
  },
];

export const dashboardNavigations = [
  {
    id: "default",
    label: "Default",
    url: "/",
    icon: <ChartPie size={18} />,
  },
  {
    id: "ecommerce",
    label: "eCommerce",
    icon: <ShoppingBag size={18} />,
    children: [{ id: "ecommerce-child1", label: "Orders", url: "/orders" }],
  },
  {
    id: "projects",
    label: "Projects",
    icon: <Folder size={18} />,
    children: [
      { id: "projects-child1", label: "CRM Admin", url: "/" },
      { id: "projects-child2", label: "Client Project", url: "/" },
      { id: "projects-child3", label: "Landing Page", url: "/" },
    ],
  },
  {
    id: "courses",
    label: "Online Courses",
    icon: <BookOpen size={18} />,
    children: [
      { id: "courses-child1", label: "JS MAstery", url: "/" },
      { id: "courses-child2", label: "AI Automation", url: "/" },
    ],
  },
];

export const pages = [
  {
    id: "user",
    label: "User Profile",
    icon: <SquareUser size={18} />,
    children: [
      { id: "overview", label: "Overview", url: "/" },
      { id: "projects", label: "Projects", url: "/" },
      { id: "campaigns", label: "Campaigns", url: "/" },
      { id: "documents", label: "Documents", url: "/" },
      { id: "followers", label: "Followers", url: "/" },
    ],
  },
  {
    id: "account",
    label: "Account",
    icon: <IdCard size={18} />,
    children: [
      { id: "account-child1", label: "My Account", url: "/" },
      { id: "account-child2", label: "Setings", url: "/" },
    ],
  },
  {
    id: "corporate",
    label: "Corporate",
    icon: <UsersRound size={18} />,
    children: [
      { id: "corporate-child1", label: "Option 1", url: "/" },
      { id: "corporate-child2", label: "Option 2", url: "/" },
    ],
  },
  {
    id: "blog",
    label: "Blog",
    icon: <BookText size={18} />,
    children: [
      { id: "blog-child1", label: "Daily Blogs", url: "/" },
      { id: "blog-child2", label: "Latest Blog", url: "/" },
    ],
  },
  {
    id: "social",
    label: "Social",
    icon: <MessageCircle size={18} />,
    children: [
      { id: "social-child1", label: "GitHub", url: "/" },
      { id: "social-child2", label: "LinkedIn", url: "/" },
      { id: "social-child2", label: "Twitter", url: "/" },
    ],
  },
];

export const notifications = [
  {
    type: "bug" as const,
    description: "You have a bug that needs to be resolve.",
    time: new Date().toISOString(),
  },
  {
    type: "register" as const,
    description: "New user registere",
    time: "2026-01-14T17:59:10.123Z",
  },
  {
    type: "bug" as const,
    description: "Andi Lane subscribed to you",
    time: "2026-01-13T12:29:10.123Z",
  },
  {
    type: "subscription" as const,
    description: "You have a bug that needs to be resolve.",
    time: "2026-01-14T01:29:10.123Z",
  },
];

export const activities = [
  {
    type: "user" as const,
    description: "You have a bug that needs to be resolve.",
    time: new Date().toISOString(),
    user: {
      name: "Hemant Sharma",
      image: "/3D05.png",
    },
  },
  {
    type: "user" as const,
    description: "Release a new version",
    time: "2026-01-14T17:59:10.123Z",
    user: {
      name: "Robert Phill",
      image: "/Female05.png",
    },
  },
  {
    type: "user" as const,
    description: "Submitted a bug",
    time: "2026-01-14T01:29:10.123Z",
    user: {
      name: "Dillip Singh",
      image: "/3D08.png",
    },
  },
  {
    type: "user" as const,
    description: "Modified A data in Page X",
    time: "2026-01-13T12:29:10.123Z",
    user: {
      name: "Elbert Fntch",
      image: "/Male07.png",
    },
  },
  {
    type: "user" as const,
    description: "Deleted a page in Project X",
    time: "2026-01-10T12:29:10.123Z",
    user: {
      name: "JK Roy",
      image: "/Male11.png",
    },
  },
];

export const contacts = [
  {
    id: "1",
    name: "Natali Craig",
    image: "/Female15.png",
  },
  {
    id: "2",
    name: "Drew Cano",
    image: "/Male08.png",
  },
  {
    id: "2",
    name: "Orlando Diggs",
    image: "/Male06.png",
  },
  {
    id: "3",
    name: "Andi Lane",
    image: "/Female08.png",
  },
  {
    id: "4",
    name: "Kate Morrison",
    image: "/Female09.png",
  },
  {
    id: "5",
    name: "Koray Okumus",
    image: "/3D03.png",
  },
];

export type OrderStatus =
  | "IN_PROGRESS"
  | "COMPLETE"
  | "PENDING"
  | "APPROVED"
  | "REJECTED";

export interface Order {
  orderId: string;
  userName: string;
  userImage: string;
  projectName: string;
  address: string;
  date: string | Date;
  status: OrderStatus;
  status_text: string;
  status_color: string;
  dark_status_color?: string;
}

export const initialOrders: Order[] = [
  {
    orderId: "#CM9081",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: new Date().toISOString(),
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9082",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-15T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9083",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-16T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9084",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "2026-01-17T17:59:10.123Z",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM9085",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-17T04:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM9086",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "2026-01-16T07:10:10.123Z",
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9087",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-17T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9088",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-11T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9089",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "2025-01-14T17:59:10.123Z",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM9090",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-14T17:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM9388",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-11T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9685",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-17T04:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM9020",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: new Date().toISOString(),
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM8586",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "2026-01-16T07:10:10.123Z",
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9017",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "2026-01-17T17:59:10.123Z",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM9784",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "2026-01-17T17:59:10.123Z",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM8982",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-15T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9014",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-17T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9190",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-14T17:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM9015",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "2026-01-16T07:10:10.123Z",
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9024",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-17T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9289",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "2025-01-14T17:59:10.123Z",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM9081",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: new Date().toISOString(),
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9028",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-16T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM8190",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-14T17:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM8487",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-17T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9026",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-17T04:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM8883",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-16T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9029",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-15T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9016",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-17T04:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM9586",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "2026-01-16T07:10:10.123Z",
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM8685",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-17T04:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM9030",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: new Date().toISOString(),
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9487",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-17T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9013",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-11T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9011",
    userName: "Andie Lane",
    userImage: "Female08.png",
    projectName: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "2026-01-14T17:59:10.123Z",
    status: "REJECTED",
    status_text: "Rejected",
    status_color: "#1c1c1c",
    dark_status_color: "rgba(255, 255, 255, 0.4)",
  },
  {
    orderId: "#CM8081",
    userName: "Natali Craig",
    userImage: "Female15.png",
    projectName: "Landing Page",
    address: "Meadow Lane Oakland",
    date: new Date().toISOString(),
    status: "IN_PROGRESS",
    status_text: "In Progress",
    status_color: "#8a8cd9",
  },
  {
    orderId: "#CM9982",
    userName: "Kate Morrison",
    userImage: "Female09.png",
    projectName: "CRM Admin Pages",
    address: "Larry San Francisco",
    date: "2026-01-15T17:59:10.123Z",
    status: "COMPLETE",
    status_text: "Complete",
    status_color: "#4aa785",
  },
  {
    orderId: "#CM9027",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "2026-01-17T17:59:10.123Z",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM8289",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "2025-01-14T17:59:10.123Z",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
  {
    orderId: "#CM9018",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-16T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9883",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-16T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM8388",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-11T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM9023",
    userName: "Drew Cano",
    userImage: "Male08.png",
    projectName: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "2026-01-11T17:59:10.123Z",
    status: "PENDING",
    status_text: "Pending",
    status_color: "#59a8d4",
  },
  {
    orderId: "#CM8784",
    userName: "Orlando Diggs",
    userImage: "Male06.png",
    projectName: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "2026-01-17T17:59:10.123Z",
    status: "APPROVED",
    status_text: "Approved",
    status_color: "#ffc555",
  },
];
